server:
  port: 8081
  servlet:
    context-path: /keycloakservice

spring:
  # 使用指定的配置文件
  profiles:
    active: dev
  ### THYMELEAF (THYMELEAF AutoConfiguration)
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  type-aliases-package: com.xcl.keycloakservice.apply.**.model
  mapper-locations: mapper/**/*Mapper.xml
  config-location: classpath:config/sqlMapConfig.xml



